name: PR to master branch

on:
  pull_request:
    branches:
      - master

jobs: 
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run build
        run: go build github.com/bragov4ik/go-kys/...
      - name: Lint via golint
        uses: golangci/golangci-lint-action@v2
      - name: Run tests
        run: go test github.com/bragov4ik/go-kys/...
      - name: Mutation testing
        uses: rescDev/go-mutesting-action@v1.0.0
