name: PR to master branch

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Should be more than 1 for codecov to work
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check formating
        run: go fmt ./... && git diff --quiet
      - name: Lint via golint
        uses: golangci/golangci-lint-action@v2
      - name: Run build
        run: go build github.com/bragov4ik/go-kys/...

      - name: Run tests
        run: go test github.com/bragov4ik/go-kys/...
      - name: Mutation testing
        uses: rescDev/go-mutesting-action@v1.0.0
        with:
            targets: pkg/...

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic github.com/bragov4ik/go-kys/pkg/...
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.COVERAGE_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
